# docker-compose.yml
version: '3.8'

services:
  # This is the name of our service
  app:
    # Tell Docker Compose to build the image using the Dockerfile in this directory
    build: .
    # The 'image' key now names the image that Compose builds
    image: note-rest-api:tag
    ports:
      # Map port 8050 on the host to port 8050 in the container
      - "8050:8050"
    # Tell Docker Compose to load variables from the .env file
    env_file:
      - .env